kumuluzee:
  name: iskanje-service
  env:
    name: dev
  version: 1.0.0
  server:
    http:
      port: 8080
    base-url: http://192.168.99.100:8080
  config:
    consul:
      agent: http://192.168.99.100:8500
  discovery:
    consul:
      agent: http://192.168.99.100:8500
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
    metrics:
      web-instrumentation:
        - name: iskanje-endpoint
          url-pattern: /v1/iskanje/*

rest-properties:
  maintenance-mode: false
  maintenance-mode-quest-api: false
  broken: false

external-api:
  distanceapi: http://www.mapquestapi.com/directions/v2/routematrix?key=o2AXh5wFGHwUVSg7q6TKNm9D61GBikii
